# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa2a375d5e1e7b31ec4df3301c4399b1402d0d77a5a4f46c20397fe5dc6aa3878bc091a0b00af91f4e96a480be1e00511465e0aa39d23a0cbdd11465ab68603

test:
  secret_key_base: e076045de5947ef9782e3ed9969c15d864fcc349ee21ff778ade26e79364a2a3acd3e759ccd451b9591d9fa13efcd34a0f772a25dbfa18d3803c66f7505f63d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
