# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# db/seeds.rb
Ingredient.create(name: "Acerola")
Ingredient.create(name: "Aged Brandy")
Ingredient.create(name: "Aged Rum From Martinique ")
Ingredient.create(name: "Aged Rum of Cuban Type ")
Ingredient.create(name: "Aged Rum of Haitian Type ")
Ingredient.create(name: "Aged Rum of Jamaican Type")
Ingredient.create(name: "Almond ")
Ingredient.create(name: "Apple Flavored Vodka ")
Ingredient.create(name: "Apricot Brandy ")
Ingredient.create(name: "Avocado")
Ingredient.create(name: "Balsamico Vinegar")
Ingredient.create(name: "Barack Palinka ")
Ingredient.create(name: "Basil")
Ingredient.create(name: "Beef Consomme")
Ingredient.create(name: "Bison Grass Flavored Vodka ")
Ingredient.create(name: "Blackberry Brandy")
Ingredient.create(name: "Blanco ")
Ingredient.create(name: "Boiling Water")
Ingredient.create(name: "Brown sauce")
Ingredient.create(name: "Brown Sugar")
Ingredient.create(name: "Butter ")
Ingredient.create(name: "Cacao Bean ")
Ingredient.create(name: "Canadian Whisky")
Ingredient.create(name: "Carrot ")
Ingredient.create(name: "Cashew nut ")
Ingredient.create(name: "Celery ")
Ingredient.create(name: "Celery Salt")
Ingredient.create(name: "Cherry Flavored Vodka")
Ingredient.create(name: "Cherry Tomato")
Ingredient.create(name: "Chilean Hot Pepper ")
Ingredient.create(name: "Chocolate")
Ingredient.create(name: "Chocolate Cookie ")
Ingredient.create(name: "Chocolate Sauce")
Ingredient.create(name: "Cilantro ")
Ingredient.create(name: "Cinnamon ")
Ingredient.create(name: "Cinnamon Cane")
Ingredient.create(name: "Citrus Rum ")
Ingredient.create(name: "Cloves ")
Ingredient.create(name: "Cocktail Onion ")
Ingredient.create(name: "Coconut Cream")
Ingredient.create(name: "Coffee Bean")
Ingredient.create(name: "coffeeIce Cream, Coffee Flavored ")
Ingredient.create(name: "Cranberry Flavored Vodka ")
Ingredient.create(name: "Cream of Coconut ")
Ingredient.create(name: "Crushed Ice")
Ingredient.create(name: "Cseresznye Palinka ")
Ingredient.create(name: "Cucumber ")
Ingredient.create(name: "Dark Rum (aged)")
Ingredient.create(name: "Dark Rum of Jamaican Type")
Ingredient.create(name: "Double Espresso")
Ingredient.create(name: "Dry Vermouth ")
Ingredient.create(name: "Eau de Vie ")
Ingredient.create(name: "Egg (yolk and white) ")
Ingredient.create(name: "Egg White")
Ingredient.create(name: "Egg Yolk ")
Ingredient.create(name: "Espresso ")
Ingredient.create(name: "Estate Rum ")
Ingredient.create(name: "Flowers (edible) ")
Ingredient.create(name: "Gherkin")
Ingredient.create(name: "Gin (old Tom)")
Ingredient.create(name: "Ginger ")
Ingredient.create(name: "Ginger (grated)")
Ingredient.create(name: "Grape Schnapps ")
Ingredient.create(name: "Green Olive")
Ingredient.create(name: "Ground Black Pepper")
Ingredient.create(name: "Half And Half")
Ingredient.create(name: "Honey")
Ingredient.create(name: "Honey Flavored Vodka ")
Ingredient.create(name: "Honey Syrup")
Ingredient.create(name: "Horseradish")
Ingredient.create(name: "Hot Sauce")
Ingredient.create(name: "Ice Cubes")
Ingredient.create(name: "Infused Vodka")
Ingredient.create(name: "inMilk, Frozen In Cubes")
Ingredient.create(name: "Irish Whiskey")
Ingredient.create(name: "Jalapeno ")
Ingredient.create(name: "Lemon Curd ")
Ingredient.create(name: "Lemon Verbena")
Ingredient.create(name: "Lemongrass ")
Ingredient.create(name: "Level Vodka")
Ingredient.create(name: "Light Rum")
Ingredient.create(name: "Malibu Rum ")
Ingredient.create(name: "Mango Rum")
Ingredient.create(name: "Marsmallows")
Ingredient.create(name: "Marzipan ")
Ingredient.create(name: "Milk ")
Ingredient.create(name: "Mint Leaf")
Ingredient.create(name: "mustard")
Ingredient.create(name: "Navy Rum ")
Ingredient.create(name: "Nutmeg ")
Ingredient.create(name: "Orange Flavored Brandy ")
Ingredient.create(name: "Orange Flavored Vodka")
Ingredient.create(name: "Orange Rum ")
Ingredient.create(name: "Orange Sorbet")
Ingredient.create(name: "orangeIce Cream, Orange Flavored ")
Ingredient.create(name: "Overproof Rum")
Ingredient.create(name: "Paprika")
Ingredient.create(name: "Peach Brandy ")
Ingredient.create(name: "Petals (edible)")
Ingredient.create(name: "Petals (edible)")
Ingredient.create(name: "Pineapple Rum")
Ingredient.create(name: "Pink Peppers ")
Ingredient.create(name: "Pistachio Nut")
Ingredient.create(name: "Plum Brandy")
Ingredient.create(name: "Plymouth Fruit Cup ")
Ingredient.create(name: "Port, White")
Ingredient.create(name: "Prune Eau de Vie ")
Ingredient.create(name: "Raspberry Rum")
Ingredient.create(name: "Reposado Tequila ")
Ingredient.create(name: "Rosemary ")
Ingredient.create(name: "Rum Banana Flavored")
Ingredient.create(name: "Rum Cherry Flavored")
Ingredient.create(name: "Rum of Haitian Type")
Ingredient.create(name: "Runny Honey")
Ingredient.create(name: "Rye Whiskey")
Ingredient.create(name: "Saffron")
Ingredient.create(name: "Salt ")
Ingredient.create(name: "Scotch Whisky")
Ingredient.create(name: "Sparkly grape")
Ingredient.create(name: "Spiced Rum ")
Ingredient.create(name: "Star Anise ")
Ingredient.create(name: "Sugar Cube (brown) ")
Ingredient.create(name: "Sugar Cube (white) ")
Ingredient.create(name: "Sugar, Superfine ")
Ingredient.create(name: "Swizzle Stick")
Ingredient.create(name: "teaEarl Grey Tea Syrup ")
Ingredient.create(name: "Tomato ")
Ingredient.create(name: "Vanilla")
Ingredient.create(name: "Vanilla Ice Cream")
Ingredient.create(name: "Vanilla Rum")
Ingredient.create(name: "Wasabi Paste ")
Ingredient.create(name: "Water")
Ingredient.create(name: "White Chocolate Stick")
Ingredient.create(name: "Woodruff Syrup ")
Ingredient.create(name: "Worcestershire Sauce ")
Ingredient.create(name: "Yoghurt")
